### Name: Benjie Gonzales Jr.

# CMSC 197 - Quiz 1

## Part 1.

• Importing important libraries by the use of the **import** function

In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [4]:
%pylab inline

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


Creating 2 1D arrays, y_hat and y

In [122]:
y_hat = np.array([30]);
y = np.array([40]);

• Initialize y_hat with 20 linearly spaced numbers between -1 and 1

In [4]:
y_hat = np.linspace(-1.0, 1.0, num=20)
y_hat

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

• Initialize y with 20 linearly spaced numbers between 0 and 1

In [3]:
y = np.linspace(0.0, 1.0, num=20)
y

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

• Compute for the shape and dimension of y_hat and y.

In [158]:
y_hat.shape

(20,)

In [159]:
y.shape

(20,)

In [160]:
y_hat.ndim

1

In [161]:
y.ndim

1

Create individual functions for each of the loss functions with y and
y_hat as parameters

### Mean Squared Error

In [11]:
def mean_squared_err(y, y_hat):
    MSE = np.square(np.subtract(y, y_hat)).mean()
    return MSE
print(mean_squared_err(y, y_hat))

0.3421052631578948


### Mean Absolute Error (MAE)

In [12]:
def mean_abs_err(y, y_hat):
    MAE = abs(np.subtract(y, y_hat)).mean()
    return MAE
print(mean_abs_err(y, y_hat))
    

0.4999999999999999


### Mean Squared Logarithmic Error:

In [38]:
def mean_squared_log_err(y, y_hat):
    if all(y_hat >= 0) == True and all(y >= 0) == True:
        MSLE = np.mean((np.log(y + 1) - np.log(y_hat + 1))**2)
        return MSLE
    else:
        invalid = "Some values are invalid. Could not perform operation."
        return invalid

print(mean_squared_log_err(y, y_hat))

Some values are invalid. Could not perform operation.


## Mean Absolute Percentage Error:

In [39]:
def mean_abs_perc_err(y, y_hat):
    if all(y) == False:
        invalid = "Some values are invalid. Could not perform operation."
        return invalid
    else:
        MAPE = np.mean(np.abs((y - y_hat)/y))*100
        return MAPE
print(mean_abs_perc_err(y, y_hat))

Some values are invalid. Could not perform operation.


 ## Each function should return the loss value (L)

In [21]:
print("Mean squared error is:", end=" ")
print(mean_squared_err(y, y_hat))
print("Mean absolute error is:", end=" ")
print(mean_abs_err(y, y_hat))
print("Mean absolute error 2nd version in is:", end=" ")
print(mean_abs_err2(y, y_hat))
print("Mean squared logarithmic error is: ", end=" ")
print(mean_squared_log_err(y, y_hat))
print("Mean absolute percent error is: ", end=" ")
print(mean_abs_perc_err(y, y_hat))

Mean squared error is: 0.3421052631578948
Mean absolute error is: 0.4999999999999999
Mean absolute error 2nd version in is: 0.9499999999999998
Mean squared logarithmic error is:  Some values are invalid
Mean absolute percent error is:  Some values are invalid


## Part 2.

In [26]:
import pandas as pd
import numpy as np

### 1. Create a 1d array M {1, 2, …16} using the arange function

In [27]:
M = np.arange(1, 17)
M

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

### 2. Reshape M into 4x4 array and store it to N

In [28]:
N = M.reshape(4, 4);
N

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 3. Get the 2nd row of N

In [34]:
N[1]

array([5, 6, 7, 8])

### 4. Get the minimum values for each column of N

In [29]:
np.min(N, axis = 0)

array([1, 2, 3, 4])

### 5. Get the locations of the minimum values for each column of N

In [35]:
np.argmin(N, axis=0)

array([0, 0, 0, 0], dtype=int64)

### 6. Get the average of the whole matrix

In [36]:
N.mean()

8.5

### 7. Create a vector V with 4 elements, each element is 1

In [66]:
V = np.array([1, 1, 1, 1]);

array([10, 26, 42, 58])

### 8. Take the dot product of N and V

In [ ]:
np.dot(N, V)